name: Keep Backend Alive

on:
  schedule:
    - cron: "*/13 * * * *" # Every 13 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -X GET https://grocery-list-app-backend.onrender.com/healthz \
            --max-time 60 \
            --retry 2 \
            --retry-delay 10
